const jobs = {
  ADDED_COLLABORATOR_JOB: 'ADDED_COLLABORATOR_JOB',
  REMOVED_COLLABORATOR_JOB: 'REMOVED_COLLABORATOR_JOB',
  INVITED_COLLABORATOR_JOB: 'INVITED_COLLABORATOR_JOB',
  ADDED_MEMBER_JOB: 'ADDED_MEMBER_JOB',
  REMOVED_MEMBER_JOB: 'REMOVED_MEMBER_JOB',
  ADDED_FILE_JOB: 'ADDED_FILE_JOB',
  EDITED_FILE_JOB: 'EDITED_FILE_JOB',
  EDITED_PORTAL_DATA: 'EDITED_PORTAL_DATA',
};

module.exports = jobs;
