const jobs = {
  ADDED_FILE: 'ADDED_FILE',
  EDITED_FILE: 'EDITED_FILE',
  ADDED_COLLABORATOR: 'ADDED_COLLABORATOR',
  REGISTERED_COLLABORATOR_KEY: 'REGISTERED_COLLABORATOR_KEY',
  REMOVED_COLLABORATOR: 'REMOVED_COLLABORATOR',
  UPDATED_PORTAL_METADATA: 'UPDATED_PORTAL_METADATA',
  MINT: 'MINT',
};

module.exports = jobs;
